<?xml version="1.0" encoding="UTF-8"?><testsuite name="Chrome_390217171_Mac_OS.class" errors="5" failures="0" tests="5" time="0.0050000004">
<testcase classname="Chrome_390217171_Mac_OS.class" name="test test construct lecture class" time="0.002">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:15:31)\n    at QUnitTestCase.(anonymous function) [as test test construct lecture class] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:15:31)\n    at QUnitTestCase.(anonymous function) [as test test construct lecture class] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:15:31)\n    at QUnitTestCase.(anonymous function) [as test test construct lecture class] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at jstestdriver.PluginRegistrar.dispatch_ (http://localhost:9876/static/runner.js:1603:26)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.class" name="test test construct drive class" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:26:31)\n    at QUnitTestCase.(anonymous function) [as test test construct drive class] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:26:31)\n    at QUnitTestCase.(anonymous function) [as test test construct drive class] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:26:31)\n    at QUnitTestCase.(anonymous function) [as test test construct drive class] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.class" name="test test for hierarchy" time="0.0">
<error type="error">[{"message":"ok() assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:37:33)\n    at QUnitTestCase.(anonymous function) [as test test for hierarchy] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: ok() assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:37:33)\n    at QUnitTestCase.(anonymous function) [as test test for hierarchy] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at assert.ok (http://code.jquery.com/qunit/qunit-1.12.0.js:518:10)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:37:33)\n    at QUnitTestCase.(anonymous function) [as test test for hierarchy] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.class" name="test test for creating lecture class from json object" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:67:49)\n    at QUnitTestCase.(anonymous function) [as test test for creating lecture class from json object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:67:49)\n    at QUnitTestCase.(anonymous function) [as test test for creating lecture class from json object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:67:49)\n    at QUnitTestCase.(anonymous function) [as test test for creating lecture class from json object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.class" name="test test for creating drive class from json object" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:97:49)\n    at QUnitTestCase.(anonymous function) [as test test for creating drive class from json object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:97:49)\n    at QUnitTestCase.(anonymous function) [as test test for creating drive class from json object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/object/class_test.js:97:49)\n    at QUnitTestCase.(anonymous function) [as test test for creating drive class from json object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
</testsuite>
