<?xml version="1.0" encoding="UTF-8"?><testsuite name="Firefox_340_Mac_OS.classDB" errors="7" failures="0" tests="7" time="0.0070000007">
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test for class initialisation for the first time" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:15:24\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\ncoverage&lt;/InstrumentedTestCaseRunnerPlugin.prototype.runTestConfiguration@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:5\njstestdriver.PluginRegistrar.prototype.dispatch_@http://localhost:9876/static/runner.js:1603:11\njstestdriver.PluginRegistrar.prototype.runTestConfiguration@http://localhost:9876/static/runner.js:1693:3\njstestdriver.TestRunner.prototype.runConfiguration@http://localhost:9876/static/runner.js:2817:1\njstestdriver.TestRunner.prototype.runNextConfiguration_@http://localhost:9876/static/runner.js:2795:1\njstestdriver.TestRunner.prototype.runTests@http://localhost:9876/static/runner.js:2775:3\njstestdriver.RunTestsCommand.prototype.runTestCases_@http://localhost:9876/static/runner.js:3424:1\njstestdriver.RunTestsCommand.prototype.runTests@http://localhost:9876/static/runner.js:3416:1\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\njstestdriver.CommandExecutor.prototype.executeCommand@http://localhost:9876/static/runner.js:2995:5\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n.handleSuccess@http://localhost:9876/static/lib/jquery-min.js:141:416\n.ajax/w.onreadystatechange@http://localhost:9876/static/lib/jquery-min.js:140:1\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.deepEqual@http://code.jquery.com/qunit/qunit-1.12.0.js:593:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:15:24\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\ncoverage&lt;/InstrumentedTestCaseRunnerPlugin.prototype.runTestConfiguration@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:5\njstestdriver.PluginRegistrar.prototype.dispatch_@http://localhost:9876/static/runner.js:1603:11\njstestdriver.PluginRegistrar.prototype.runTestConfiguration@http://localhost:9876/static/runner.js:1693:3\njstestdriver.TestRunner.prototype.runConfiguration@http://localhost:9876/static/runner.js:2817:1\njstestdriver.TestRunner.prototype.runNextConfiguration_@http://localhost:9876/static/runner.js:2795:1\njstestdriver.TestRunner.prototype.runTests@http://localhost:9876/static/runner.js:2775:3\njstestdriver.RunTestsCommand.prototype.runTestCases_@http://localhost:9876/static/runner.js:3424:1\njstestdriver.RunTestsCommand.prototype.runTests@http://localhost:9876/static/runner.js:3416:1\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\njstestdriver.CommandExecutor.prototype.executeCommand@http://localhost:9876/static/runner.js:2995:5\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n.handleSuccess@http://localhost:9876/static/lib/jquery-min.js:141:416\n.ajax/w.onreadystatechange@http://localhost:9876/static/lib/jquery-min.js:140:1\n"}]</error>
</testcase>
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test for class initialisation with reloading local storage's content" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:49:24\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.equal@http://code.jquery.com/qunit/qunit-1.12.0.js:556:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:49:24\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n"}]</error>
</testcase>
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test for adding a drive class" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:72:24\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.equal@http://code.jquery.com/qunit/qunit-1.12.0.js:556:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:72:24\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n"}]</error>
</testcase>
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test for getting a class by its id" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:107:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.equal@http://code.jquery.com/qunit/qunit-1.12.0.js:556:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:107:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n"}]</error>
</testcase>
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test for checking a class's existence" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:129:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.equal@http://code.jquery.com/qunit/qunit-1.12.0.js:556:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:129:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n"}]</error>
</testcase>
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test for deleting a class from class database" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:149:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.equal@http://code.jquery.com/qunit/qunit-1.12.0.js:556:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:149:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n"}]</error>
</testcase>
<testcase classname="Firefox_340_Mac_OS.classDB" name="test test teacher close operation" time="0.001">
<error type="error">[{"message":"assertion outside test context, was @http://localhost:9876/test/test/qunit/model/database/classDB_test.js:180:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n","name":"Error","fileName":"http://code.jquery.com/qunit/qunit-1.12.0.js","lineNumber":917,"stack":".push@http://code.jquery.com/qunit/qunit-1.12.0.js:917:1\nassert.equal@http://code.jquery.com/qunit/qunit-1.12.0.js:556:3\n@http://localhost:9876/test/test/qunit/model/database/classDB_test.js:180:25\n@http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:28\njstestdriver.plugins.TestRunnerPlugin.prototype.runTest@http://localhost:9876/static/runner.js:5403:7\nrunTest@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:21\ncoverage&lt;/TestResultIterator.prototype.runNext@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:5\ncoverage&lt;/InstrumentedTestCaseRunner.prototype.run@http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:7\nbound@http://localhost:9876/static/jstestdrivernamespace.js:71:12\n"}]</error>
</testcase>
</testsuite>
